server:
  port: 9200

spring:
  data:
    rest:
      detection-strategy: annotated
  datasource:
    url: jdbc:postgresql://localhost:5432/foradz
    username: java_webservice_user
    password: MXEPqkpBEBSfD8RrjZchxDj7FwRy9qc8
  jpa:
    #show-sql: true
    properties:
      hibernate:
        #format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-request-size: -1
      max-file-size: -1
app:
  video:
    thumbnail:
      processorPath: F:\\Program Files\\ffmpeg-4.4\\bin
      infoProvider: ffprobe.exe
      generator: ffmpeg.exe
      size: 300*300
      suffix: _thumb.gif
      grabAtPercent: 40
      gifDuration: 10
  image:
    thumbnail:
      width: 600
      height: 600
      suffix: _thumb.jpg
  file-system:
    baseDir: J:\\Softwares\\Apps\\AppData\\primedia
    binDirName: bin
    storageDirName: storage
    thumbnailDirName: thumbnail
    workDirName: work
    downloadDirName: download
    logsDirName: logs
